### ISSUE TITLE
iframe wallet freezes when the user hasn't used it for a while

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#538] opened 2020-09-30 12:14 UTC
When I don't use the iframe wallet for a while, I get a problem to use my iframe wallet after a break.
I mean I don't use the sh site for a few minutes, use other tabs, then I went back to the sh site and found this:

![Знімок екрана 2020-09-30 о 2 36 13 пп](https://user-images.githubusercontent.com/69896204/94683505-550a0b80-032f-11eb-993c-5232fbf9a0fe.png)

Browsers: Chrome, FF, Brave
OS: iOS

**Comment by mradkov** [comment] 2020-09-30 12:24
Duplicate of #537

**Closed by mradkov** 2020-09-30 12:24 UTC
Labels: triage/duplicate
