### ISSUE TITLE
Error while registering name

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#783] opened 2021-01-28 12:31 UTC
Got this error when registered a name:

![names error](https://user-images.githubusercontent.com/69896204/106138509-e4f08280-6174-11eb-8cce-017924f58c36.png)

On the second attempt, the name was registered

 Superhero 1943eeb / v.0.5.0

**Comment by davidyuk** [comment] 2021-02-16 07:34
It may happen because of multiple transactions doing at the same time. Probably it may be fixed by local nonce management, see https://github.com/aeternity/aepp-sdk-js/issues/291

**Comment by marc0olo** [comment] 2021-05-04 15:21
@davidyuk from our experience during the running hackathon I am 99,99% sure this is a problem in a local development environment.

@Liubov-crypto what network did you use when that error occurred?

**Comment by Liubov-crypto** [comment] 2021-05-05 11:11
> @davidyuk from our experience during the running hackathon I am 99,99% sure this is a problem in a local development environment.
> 
> @Liubov-crypto what network did you use when that error occurred?
> 
> **note**
> 
> * the error occured for a contract call in our case. so it's not specifically for registering names but probably for any kind of tx

I used the main network.

**Comment by CedrikNikita** [comment] 2021-07-22 03:52
duplicate of #661

**Closed by CedrikNikita** 2021-07-22 03:52 UTC
