### ISSUE TITLE
Error when switching from the testnet to the mainnet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#720] opened 2020-12-08 12:22 UTC
I got this error when switching from the testnet to the mainnet: 
![переключение нода](https://user-images.githubusercontent.com/69896204/101482962-28422800-3960-11eb-9cc9-81bd483b80b2.png)

Superhero db54896 / v.0.4.2

**Comment by stanislav-slavov** [comment] 2020-12-13 12:10
The pull request is merged into develop. I am unable to reproduce it. @Liubov-crypto please check it out again.

**Comment by Liubov-crypto** [comment] 2020-12-14 09:13
Got this error in the web wallet when switched from the mainnet to the testnet:

![webwallet](https://user-images.githubusercontent.com/69896204/102062172-0aac0d00-3dfd-11eb-8522-68a4acb11fb9.png)
![1](https://user-images.githubusercontent.com/69896204/102062185-0ed82a80-3dfd-11eb-8792-6b1b9f833854.png)
![2](https://user-images.githubusercontent.com/69896204/102062191-113a8480-3dfd-11eb-96ea-6fe1799433a2.png)

**Comment by stanislav-slavov** [comment] 2020-12-14 15:09
This is a configuration problem. @IvayloPapazov will have a look.

**Comment by IvayloPapazov** [comment] 2020-12-15 14:13
What I see is that the slagger does not return "Access-Control-Allow-Origin" unlike other services. I mean, "Access-Control-Allow-Origin" should be started (or stopped) for all services or configurable.

**Comment by davidyuk** [comment] 2020-12-16 08:02
who can we ask to enable CORS headers of the middleware? cc: @mradkov

**Comment by mradkov** [comment] 2020-12-19 11:58
> who can we ask to enable CORS headers of the middleware? cc: @mradkov

Already informed Karol and @IvayloPapazov but this issue is still not fixed I think.

**Comment by mradkov** [comment] 2020-12-19 12:22
<img width="889" alt="Screenshot 2020-12-19 at 14 22 05" src="https://user-images.githubusercontent.com/13139371/102689284-95c64200-4205-11eb-9604-b3f7f79a4c1b.png">

I think the issue is only present on the swagger endpoint

**Comment by mradkov** [comment] 2021-01-21 09:57
@Liubov-crypto I think this is resolved already. Can you confirm?

**Comment by Liubov-crypto** [comment] 2021-01-21 10:54
> @Liubov-crypto I think this is resolved already. Can you confirm?

Checked, switching between networks works well.

**Comment by CedrikNikita** [comment] 2021-03-26 06:29
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.

**Closed by CedrikNikita** 2021-03-26 06:29 UTC
Labels: kind/bug, middleware, priority/high
