### ISSUE TITLE
Not all fields are translated into Chinese:

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#583] opened 2020-11-04 18:17 UTC
Not all fields are translated into Chinese:
![Знімок екрана 2020-11-04 о 1 06 50 пп](https://user-images.githubusercontent.com/69896204/98151641-286e8400-1ed9-11eb-9b64-c93c913c2219.png)
![Знімок екрана 2020-11-04 о 1 07 49 пп](https://user-images.githubusercontent.com/69896204/98151655-315f5580-1ed9-11eb-8c05-bf8bdf025389.png)
![Знімок екрана 2020-11-04 о 8 07 45 пп](https://user-images.githubusercontent.com/69896204/98151805-6a97c580-1ed9-11eb-9d9d-43faf58a97e2.png)

After claiming back, the field name changed to English
![Знімок екрана 2020-11-04 о 8 08 37 пп](https://user-images.githubusercontent.com/69896204/98151883-89965780-1ed9-11eb-999d-393d5704da62.png)

![Знімок екрана 2020-11-04 о 8 11 22 пп](https://user-images.githubusercontent.com/69896204/98152142-eabe2b00-1ed9-11eb-9d09-473326c3fc6e.png)
![Знімок екрана 2020-11-04 о 8 12 14 пп](https://user-images.githubusercontent.com/69896204/98152219-0b868080-1eda-11eb-8076-fb4c85b5a288.png)
![Знімок екрана 2020-11-04 о 8 12 41 пп](https://user-images.githubusercontent.com/69896204/98152261-1a6d3300-1eda-11eb-8b7a-41a9823ce9ee.png)

Also, if the wallet is minimized then the Chinese language is automatically changed to English. I don’t know how convenient it will be for Chinese users to constantly change the language.

_Originally posted by @Liubov-crypto in https://github.com/aeternity/superhero-wallet/issues/582#issuecomment-721892680_

**Comment by Liubov-crypto** [comment] 2020-11-19 09:15
The tokens button also needs to be translated into Chinese: 
![2020-11-19 11 12 26 дп](https://user-images.githubusercontent.com/69896204/99645725-3d5e2200-2a58-11eb-83d4-8cc2bb1376d2.jpg)
![2020-11-19 11 12 18 дп](https://user-images.githubusercontent.com/69896204/99645740-42bb6c80-2a58-11eb-8b10-ca9f2b68617d.jpg)

**Comment by davidyuk** [comment] 2021-03-15 11:57
duplicate of #887

**Closed by davidyuk** 2021-03-15 11:57 UTC
