### ISSUE TITLE
Translation of the interface into Chinese

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#505] opened 2020-09-11 16:25 UTC
Not all fields in the wallet are translated into Chinese. Version: Superhero 8a93b01 / v.0.3.3

![Знімок екрана 2020-09-11 о 6 58 32 пп](https://user-images.githubusercontent.com/69896204/92949698-31f0e800-f464-11ea-9327-e9d67e943e84.png)

![Знімок екрана 2020-09-11 о 6 59 28 пп](https://user-images.githubusercontent.com/69896204/92949765-4cc35c80-f464-11ea-8dae-b57b6c731aca.png)

![Знімок екрана 2020-09-11 о 7 00 51 пп](https://user-images.githubusercontent.com/69896204/92949802-5947b500-f464-11ea-8d69-d0b9d36ceec4.png)

![Знімок екрана 2020-09-11 о 7 02 10 пп](https://user-images.githubusercontent.com/69896204/92949860-72506600-f464-11ea-85bd-2b72963c0a85.png)

![Знімок екрана 2020-09-11 о 7 02 37 пп](https://user-images.githubusercontent.com/69896204/92949895-7f6d5500-f464-11ea-842c-52353205364a.png)

**Comment by Liubov-crypto** [comment] 2020-09-15 11:13
Not all fields in the wallet are translated into Chinese. Version: Superhero 1dfa2d4 / v.0.3.32 app for Android

![2020-09-15 1 54 37 пп](https://user-images.githubusercontent.com/69896204/93203684-8692ac80-f75d-11ea-8b26-19e22ff5a81c.jpg)
![2020-09-15 1 54 33 пп](https://user-images.githubusercontent.com/69896204/93203698-88f50680-f75d-11ea-9a90-6e4bf995fa43.jpg)
![2020-09-15 1 54 24 пп](https://user-images.githubusercontent.com/69896204/93203701-898d9d00-f75d-11ea-9c74-05d8e48d8ca1.jpg)
![2020-09-15 1 54 42 пп](https://user-images.githubusercontent.com/69896204/93203704-8a263380-f75d-11ea-924d-8709c3486ddf.jpg)
![2020-09-15 1 54 28 пп](https://user-images.githubusercontent.com/69896204/93203707-8abeca00-f75d-11ea-87a3-57707edceafd.jpg)
![2020-09-15 1 54 20 пп](https://user-images.githubusercontent.com/69896204/93203711-8b576080-f75d-11ea-87a1-6eff6a640785.jpg)
![2020-09-15 1 54 14 пп](https://user-images.githubusercontent.com/69896204/93203712-8beff700-f75d-11ea-957f-9c4f460422b5.jpg)

**Comment by davidyuk** [comment] 2021-03-15 11:56
duplicate of #887

**Closed by davidyuk** 2021-03-15 11:56 UTC
Labels: area/locale, kind/improvement
