### ISSUE TITLE
Register a name

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1143] opened 2021-06-22 13:08 UTC
Register a name in the testnet (the name was registered at 2 attempt):
![register a name in the testnet](https://user-images.githubusercontent.com/69896204/122921135-d183c500-d36a-11eb-9496-38a921e2afdb.png)

commit 9487d5a / v.0.7.2

**Comment by davidyuk** [comment] 2021-06-25 08:36
This can be fixed by switching to the nonce endpoint from https://github.com/aeternity/aeternity/issues/3662
Corresponding issue in SDK: https://github.com/aeternity/aepp-sdk-js/issues/291

**Comment by CedrikNikita** [comment] 2021-07-22 03:51
duplicate of #661

**Closed by CedrikNikita** 2021-07-22 03:51 UTC
