### ISSUE TITLE
FF extension is hidden under the browser panel

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#974] opened 2021-04-13 09:11 UTC
the FF extension is hidden under the panel and I cannot log in:
![hidden in FF](https://user-images.githubusercontent.com/69896204/114522474-1513d180-9c4c-11eb-89eb-f836fabf91b1.png)

Also reproducible in the latest release.

**Comment by gorbak25** [comment] 2021-04-13 09:15
Got the same issue :(

**Comment by davidyuk** [comment] 2021-04-13 14:42
duplicate of #973

**Closed by davidyuk** 2021-04-13 14:42 UTC
