### ISSUE TITLE
Adding the transfer function for .chain names

### ISSUE THREAD

**Issue by SuperheroDex** [aeternity/superhero-wallet#1642] opened 2022-10-15 09:03 UTC
Maybe this is something to have a look at for adding the transfer function for .chain names to the SuperHero wallet
![Screenshot_2022-10-05-12-03-56-650_com microsoft emmx](https://user-images.githubusercontent.com/112299423/195978426-e1fb46e4-dc45-4063-9df1-2ff3a6137275.jpg)

**Comment by CedrikNikita** [comment] 2023-06-12 16:31
duplicate of #1320

**Closed by CedrikNikita** 2023-06-12 16:31 UTC
